import { useState } from "react";
import Head from "next/head";

export default function Home() {
	const styles = {
		inputContainer: "w-full h-10 flex",
		input: "w-3/4 h-full rounded-md shadow-lg",
		inputName: "w-1/4 text-lg",
	};

	const [percentages, setPercentages] = useState(
		{ snatch: 0 },
		{ cj: 0 },
		{ bs: 0 }
	);

	const handleChange = (e) => {
		const { name, value } = e.target;
		setPercentages({
			...percentages,
			[name]: value,
		});
	};

	return (
		<div className="p-5 h-screen bg-purple-100">
			<Head>
				<title>Load Your Weights</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="space-y-5">
				<div className={styles.inputContainer}>
					<p className={styles.inputName}>
						Snatch
					</p>
					<input
						name="snatch"
						className={styles.input}
						onChange={handleChange}
						value={percentages.snatch}
					/>
				</div>
				<div className={styles.inputContainer}>
					<p className={styles.inputName}>
						Clean & Jerk
					</p>
					<input
						name="cj"
						className={styles.input}
						onChange={handleChange}
						value={percentages.cj}
					/>
				</div>
				<div className={styles.inputContainer}>
					<p className={styles.inputName}>
						Back Squat
					</p>
					<input
						name="bs"
						className={styles.input}
						onChange={handleChange}
						value={percentages.bs}
					/>
				</div>
			</main>
		</div>
	);
}
